services:

  db:
    image: postgres:16
    container_name: hastane-yonetim-db
    environment:
      POSTGRES_DB: hastane
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: hastane-yonetim-app
    container_name: hastane-yonetim-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hastane
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  selenium:
    image: seleniarm/standalone-chromium:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"
    shm_size: 2gb
