services:

  hastane-yonetim-db:
    image: postgres:16
    container_name: hastane-yonetim-db
    environment:
      POSTGRES_DB: hastane
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  hastane-yonetim-app:
    build: .
    container_name: hastane-yonetim-app
    depends_on:
      hastane-yonetim-db:
        condition: service_healthy
    ports:
      - "9091:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://hastane-yonetim-db:5432/hastane
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  selenium-chrome:
    image: seleniarm/standalone-chromium:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2gb
